# nushell config (new Mac). starship / zoxide / atuin / mise hooks are generated by install-core.sh
# into ($nu.data-dir)/vendor/autoload and load automatically.
$env.config.show_banner = false
$env.config.edit_mode = "vi"
$env.config.history.file_format = "sqlite"

alias vim = nvim
alias lg = lazygit
alias c = clear
alias gs = git status -s
alias gd = git diff
alias glog = git log --oneline --graph --all
alias tns = tmux-sessionizer
